/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DpIndexRouteImport } from './routes/dp/index'
import { Route as DpIdRouteImport } from './routes/dp/$id'
import { Route as PathfindingIndexRouteImport } from './routes/pathfinding/index'
import { Route as PathfindingIdRouteImport } from './routes/pathfinding/$id'
import { Route as SortingIndexRouteImport } from './routes/sorting/index'
import { Route as SortingIdRouteImport } from './routes/sorting/$id'
import { Route as TreesIndexRouteImport } from './routes/trees/index'
import { Route as TreesIdRouteImport } from './routes/trees/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DpIndexRoute = DpIndexRouteImport.update({
  id: '/dp/',
  path: '/dp/',
  getParentRoute: () => rootRouteImport,
} as any)
const DpIdRoute = DpIdRouteImport.update({
  id: '/dp/$id',
  path: '/dp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PathfindingIndexRoute = PathfindingIndexRouteImport.update({
  id: '/pathfinding/',
  path: '/pathfinding/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathfindingIdRoute = PathfindingIdRouteImport.update({
  id: '/pathfinding/$id',
  path: '/pathfinding/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingIndexRoute = SortingIndexRouteImport.update({
  id: '/sorting/',
  path: '/sorting/',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingIdRoute = SortingIdRouteImport.update({
  id: '/sorting/$id',
  path: '/sorting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesIndexRoute = TreesIndexRouteImport.update({
  id: '/trees/',
  path: '/trees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesIdRoute = TreesIdRouteImport.update({
  id: '/trees/$id',
  path: '/trees/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dp/$id': typeof DpIdRoute
  '/pathfinding/$id': typeof PathfindingIdRoute
  '/sorting/$id': typeof SortingIdRoute
  '/trees/$id': typeof TreesIdRoute
  '/dp/': typeof DpIndexRoute
  '/pathfinding/': typeof PathfindingIndexRoute
  '/sorting/': typeof SortingIndexRoute
  '/trees/': typeof TreesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dp/$id': typeof DpIdRoute
  '/pathfinding/$id': typeof PathfindingIdRoute
  '/sorting/$id': typeof SortingIdRoute
  '/trees/$id': typeof TreesIdRoute
  '/dp': typeof DpIndexRoute
  '/pathfinding': typeof PathfindingIndexRoute
  '/sorting': typeof SortingIndexRoute
  '/trees': typeof TreesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dp/$id': typeof DpIdRoute
  '/pathfinding/$id': typeof PathfindingIdRoute
  '/sorting/$id': typeof SortingIdRoute
  '/trees/$id': typeof TreesIdRoute
  '/dp/': typeof DpIndexRoute
  '/pathfinding/': typeof PathfindingIndexRoute
  '/sorting/': typeof SortingIndexRoute
  '/trees/': typeof TreesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dp/$id'
    | '/pathfinding/$id'
    | '/sorting/$id'
    | '/trees/$id'
    | '/dp/'
    | '/pathfinding/'
    | '/sorting/'
    | '/trees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dp/$id'
    | '/pathfinding/$id'
    | '/sorting/$id'
    | '/trees/$id'
    | '/dp'
    | '/pathfinding'
    | '/sorting'
    | '/trees'
  id:
    | '__root__'
    | '/'
    | '/dp/$id'
    | '/pathfinding/$id'
    | '/sorting/$id'
    | '/trees/$id'
    | '/dp/'
    | '/pathfinding/'
    | '/sorting/'
    | '/trees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DpIdRoute: typeof DpIdRoute
  PathfindingIdRoute: typeof PathfindingIdRoute
  SortingIdRoute: typeof SortingIdRoute
  TreesIdRoute: typeof TreesIdRoute
  DpIndexRoute: typeof DpIndexRoute
  PathfindingIndexRoute: typeof PathfindingIndexRoute
  SortingIndexRoute: typeof SortingIndexRoute
  TreesIndexRoute: typeof TreesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp/': {
      id: '/dp/'
      path: '/dp'
      fullPath: '/dp/'
      preLoaderRoute: typeof DpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp/$id': {
      id: '/dp/$id'
      path: '/dp/$id'
      fullPath: '/dp/$id'
      preLoaderRoute: typeof DpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathfinding/': {
      id: '/pathfinding/'
      path: '/pathfinding'
      fullPath: '/pathfinding/'
      preLoaderRoute: typeof PathfindingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathfinding/$id': {
      id: '/pathfinding/$id'
      path: '/pathfinding/$id'
      fullPath: '/pathfinding/$id'
      preLoaderRoute: typeof PathfindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting/': {
      id: '/sorting/'
      path: '/sorting'
      fullPath: '/sorting/'
      preLoaderRoute: typeof SortingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting/$id': {
      id: '/sorting/$id'
      path: '/sorting/$id'
      fullPath: '/sorting/$id'
      preLoaderRoute: typeof SortingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/': {
      id: '/trees/'
      path: '/trees'
      fullPath: '/trees/'
      preLoaderRoute: typeof TreesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/$id': {
      id: '/trees/$id'
      path: '/trees/$id'
      fullPath: '/trees/$id'
      preLoaderRoute: typeof TreesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DpIdRoute: DpIdRoute,
  PathfindingIdRoute: PathfindingIdRoute,
  SortingIdRoute: SortingIdRoute,
  TreesIdRoute: TreesIdRoute,
  DpIndexRoute: DpIndexRoute,
  PathfindingIndexRoute: PathfindingIndexRoute,
  SortingIndexRoute: SortingIndexRoute,
  TreesIndexRoute: TreesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
